### DESeq
CountTable = read.table("merged_counts.txt", header=TRUE, row.names=1)
Design = data.frame(row.names=colnames(CountTable), condition=c("embryo","embryo","embryo","root","root","root"))
condition = factor( c("embryo","embryo","embryo","root","root","root") )
library( "DESeq" )
cds = newCountDataSet( CountTable, condition )
cds = estimateSizeFactors( cds )
cds = estimateDispersions(cds)
sizeFactors( cds )
head( counts( cds, normalized=TRUE ) )
jpeg("cds.jpg")
plotDispEsts( cds )
dev.off()
head( fData(cds) )
res = nbinomTest(cds, "embryo", "root" )
head(res)
jpeg("scatter.jpg")
plotMA(res)
dev.off()
jpeg("hist.jpg")
hist(res$pval, breaks=100, col="skyblue", border="slateblue", main="")
dev.off()
write.table(res, file="embryo_vs_root.txt",sep="\t")
