rm(list=ls(all=TRUE))
library(GenomicRanges, quietly=T)
library(bigmemory, quietly=T)
library(data.table, quietly=T)
source("/work/02114/wonaya/scripts/base.r")
file.list=list("B73_all3/CHG_B73_all3_R1_bt202_chr4.methylKit","Tx303_all3/CHG_Tx303_all3_bt202_chr4.methylKit")

myobj=read(file.list, sample.id=list("B73","Mo17"), assembly="B73",treatment=c(0,1),context="CpG", resolution="base")

file.list=list("SRR641618/CpG_SRR641618_aa_bismark_bt2.sam_chr16.methylKit","SRR641628/CpG_SRR641628_aa_bismark_bt2.sam_chr16.methylKit")
myobj=read(file.list, sample.id=list("test1","test2"), assembly="HG19",treatment=c(0,1),context="CpG", resolution="base")

meth=unite(myobj, destrand=FALSE)
rm(valid.methylRawObj)
rm(file.list)
rm(read)
rm(myobj)
gc()
source("/work/02114/wonaya/scripts/diffMeth.R")
myDiff=calculateDiffMeth(meth,num.cores=5)
myDiff.sub=myDiff[myDiff$pvalue<0.1 & abs(myDiff$meth.diff) > 25,]
rm(meth)
gc()
source("/work/02114/wonaya/scripts/eDMR_test.R")
myDMR=eDMR(myDiff,step=100,dist="none",DMC.qvalue=1,DMC.methdiff=25,num.DMCs=1,num.CpGs=3,DMR.methdiff=20,plot=FALSE,main="example",mode=1)
myDMR=eDMR(myDiff,step=100,dist="none",DMC.methdiff=25,num.DMCs=1,num.CpGs=3,plot=FALSE,main="example",mode=1)
myDMR=eDMR(myDiff,step=100,dist="none",DMC.qvalue=0.01,DMC.methdiff=25,num.DMCs=1,num.CpGs=3,DMR.methdiff=20,plot=FALSE,main="example",mode=1)
myDMR.sig=filter.dmr(myDMR, DMR.qvalue=0.05, mean.meth.diff=20, num.CpGs=3, num.DMCs=1)
myDMR.sig.df <- as.data.frame(myDMR.sig)
write.table(myDMR.sig.df, file="test.txt", sep="\t")

library(GenomicRanges, quietly=T)
library(bigmemory, quietly=T)
library(data.table, quietly=T)
source("/work/02114/wonaya/scripts/base.r")
file.list=list("B73_all3/CpG_context_B73_all3_bt202_chr10.methylKit","Mo17_all3/CpG_context_Mo17_all3_bt202_chr10.methylKit")
myobj=read(file.list, sample.id=list("B73","Oh43"), assembly="B73",treatment=c(0,1),context="CpG", resolution="base")
meth=unite(myobj, destrand=FALSE)
rm(valid.methylRawObj)
rm(file.list)
rm(read)
rm(myobj)
gc()
source("/work/02114/wonaya/scripts/diffMeth.R")
myDiff=calculateDiffMeth(meth,num.cores=5)
myDiff.sub=myDiff[myDiff$pvalue<0.1 & abs(myDiff$meth.diff) > 25,]
rm(meth)
gc()
source("/work/02114/wonaya/scripts/eDMR_test.R")
myDMR=eDMR(myDiff,step=100,dist="none",DMC.methdiff=25,num.DMCs=1,num.CpGs=3,DMR.methdiff=20,plot=FALSE,main="example",mode=1)
myDMR.sig=filter.dmr(myDMR, mean.meth.diff=20, num.CpGs=3, num.DMCs=1)
myDMR.sig.df <- as.data.frame(myDMR.sig)
write.table(myDMR.sig.df, file="test.txt", sep="\t")
