args <- commandArgs(TRUE)
library(GenomicRanges, quietly=T)
library(bigmemory, quietly=T)
library(data.table, quietly=T)
source("/work/02114/wonaya/scripts/base.r")
file.list=list(args[1],args[2])
myobj=read(file.list, sample.id=list(args[3],args[4]), assembly="HG19",treatment=c(0,1),context=args[5], resolution="base")
meth=unite(myobj, destrand=FALSE)
rm(valid.methylRawObj)
rm(file.list)
rm(read)
rm(myobj)
gc()
source("/work/02114/wonaya/scripts/diffMeth.R")
myDiff=calculateDiffMeth(meth)
rm(meth)
gc()
source("/work/02114/wonaya/scripts/eDMR_test.R")
myDMR=eDMR(myDiff,step=100,dist=100,plot=FALSE,main="example",mode=1)
myDMR.sig=filter.dmr(myDMR,num.DMCs=1)
myDMR.sig.df <- as.data.frame(myDMR.sig)
write.table(myDMR.sig.df, file=args[6], sep="\t")
