args <- commandArgs(TRUE) 
library(methylKit)
file.list=list("CHH_context_B73_all3_bt202_chr1.methylKit", "../Mo17_all3/CHH_context_Mo17_all3_bt202_chr1.methylKit")
myobj=read(file.list,sample.id=list("B73","Mo17"),assembly="B73",treatment=c(0,1),context="CpG",resolution="base")
meth=unite(myobj, destrand=FALSE)
myDiff=calculateDiffMeth(meth)
con <- url("http://edmr.googlecode.com/files/eDMR.v.0.5.1.R")
source(con)
close(con)
myDiff
myDMR=eDMR(myDiff,step=100,dist="none",DMC.qvalue=0.01,DMC.methdiff=25,num.DMCs=1,num.CpGs=3,DMR.methdiff=20,plot=FALSE,main="example",mode=1)
myDMR.sig=filter.dmr(myDMR, DMR.qvalue=0.05, mean.meth.diff=20, num.CpGs=3, num.DMCs=1)
myDMR.sig.df <- as.data.frame(myDMR.sig)
write.table(myDMR.sig.df, file="CpG_all_dmr.txt", sep="\t")
gc()
