args <- commandArgs(TRUE) 
library(methylKit)
file.list=list(args[1],args[2])
file.list
myobj=read(file.list,sample.id=list("B73","Mo17"),assembly="B73",treatment=c(0,1),context="CHH",resolution="base")
meth=unite(myobj, destrand=FALSE)
tiles = tileMethylCounts(myobj,win.size=1000,step.size=1000)
myDiff=calculateDiffMeth(meth)
source("http://edmr.googlecode.com/files/eDMR.v.0.4.R")
myMixmdl=myDiff.to.mixmdl(myDiff)
myDMR=eDMR(myDiff,step=100,dist="none",DMC.qvalue=0.01,DMC.methdiff=25,num.DMCs=1,num.CpGs=3,DMR.methdiff=20,plot=FALSE,main="example",mode=1)
myDMR.sig=filter.dmr(myDMR, DMR.qvalue=0.05, mean.meth.diff=20, num.CpGs=3, num.DMCs=1)
myDMR.sig.df <- as.data.frame(myDMR.sig)
write.table(myDMR.sig.df, file=args[3], sep="\t")
gc()

